// Dev rig only. Absent from any build that does not define PBJ_DRIVE,
// which is every build that ships — see PBAndJ.Mod.csproj and
// `make check-no-drive-channel`.
#if PBJ_DRIVE
using System;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using QFSW.QC;
using UnityEngine;

namespace PBAndJ.Mod.Net
{
    /// <summary>
    /// Step 0 of the drive rig: does Quantum Console work when nobody has opened
    /// it?
    /// </summary>
    /// <remarks>
    /// The rig's whole mechanism is
    /// <c>QuantumConsoleProcessor.InvokeCommand(string)</c>, and three things it
    /// depends on live inside <c>QFSW.QC.dll</c>, which is not decompiled and
    /// cannot be read: whether <c>QuantumConsole.Instance</c> exists before the
    /// console UI is first shown, whether the command table is generated by then,
    /// and whether generating it discards commands the mod added earlier through
    /// <c>TryAddCommand</c>.
    /// <para>
    /// The first of those is not a nicety. <c>ScenarioUtility.ForceScenarioAndArea</c>
    /// calls <c>QuantumConsole.Instance.LogToConsole</c> unguarded at
    /// <c>:1377</c>, <c>:1408</c> and <c>:1413</c> — all of them <em>before</em>
    /// it reaches <c>EnterCombat</c> at <c>:1416</c>. So if <c>Instance</c> is
    /// null on a machine nobody has opened the console on, <c>ow.load-scenario</c>
    /// does not merely fail to log: it throws on the way in and never starts the
    /// fight. That command is the rig's primary actuator.
    /// </para>
    /// <para>
    /// Hence a probe rather than a plan. It runs once, from the frame pump, with
    /// no console ever opened, and it is deliberately read-only: it reports what
    /// is there and invokes one of <em>our</em> commands, never a game command
    /// with side effects.
    /// </para>
    /// </remarks>
    [ExcludeFromCodeCoverage]
    internal static class DriveProbeGlue
    {
        /// <summary>
        /// Frames to let pass before probing.
        /// </summary>
        /// <remarks>
        /// The pump starts inside <c>Heartbeat.Update</c>, which begins running
        /// before the game has finished standing its singletons up. Probing on
        /// frame one would measure the loading screen rather than the resting
        /// state and report a null that resolves a moment later.
        /// </remarks>
        private const int SettleFrames = 600;

        private static int frames;
        private static bool probed;

        /// <summary>Called every frame from the <c>Heartbeat.Update</c> postfix.</summary>
        internal static void Tick()
        {
            if (probed)
            {
                return;
            }

            frames++;
            if (frames < SettleFrames)
            {
                return;
            }

            probed = true;
            try
            {
                Probe();
            }
            catch (Exception e)
            {
                // The probe existing must never be why the game stops working.
                Debug.LogWarning("[pb-and-j] qc probe failed: "
                    + e.GetType().Name + ": " + e.Message);
            }
        }

        /// <summary>
        /// Registers <c>pbj.qc-probe</c>. Lives here rather than in
        /// <c>NetGlue.RegisterConsoleCommands</c> so that the whole rig can be
        /// compiled out without leaving a dangling reference in shipping code.
        /// </summary>
        internal static void RegisterConsoleCommand()
        {
            var method = typeof(DriveProbeGlue).GetMethod(
                nameof(QcProbe), BindingFlags.Static | BindingFlags.Public,
                null, new Type[0], null);
            QuantumConsoleProcessor.TryAddCommand(new CommandData(method, "pbj.qc-probe"));
        }

        /// <summary>The <c>pbj.qc-probe</c> console command, to re-run by hand.</summary>
        /// <remarks>
        /// Reachable only if command registration itself worked, which is exactly
        /// what the automatic run does not assume — <c>ModLink.OnLoadEnd</c> is
        /// downstream of a <c>PatchAll</c> throw, so a half-patched build has no
        /// console commands at all. The automatic run is the real measurement;
        /// this is for asking again after opening the console, which is the
        /// interesting comparison.
        /// </remarks>
        public static string QcProbe()
        {
            probed = true;
            try
            {
                Probe();
                return "[pb-and-j] qc probe written to the log";
            }
            catch (Exception e)
            {
                return "[pb-and-j] qc probe failed: " + e.GetType().Name + ": " + e.Message;
            }
        }

        private static void Probe()
        {
            // Read through a local so a null Instance is reported rather than
            // thrown on, which is the entire question being asked.
            var instance = QuantumConsole.Instance;
            Debug.Log("[pb-and-j] qc probe | QuantumConsole.Instance "
                + (instance == null ? "IS NULL" : "exists")
                + " | console " + (instance != null && instance.IsActive ? "active" : "not active"));

            Debug.Log("[pb-and-j] qc probe | table generated "
                + QuantumConsoleProcessor.TableGenerated
                + " | generating " + QuantumConsoleProcessor.TableIsGenerating
                + " | commands " + QuantumConsoleProcessor.LoadedCommandCount);

            // Our own command, chosen because it has no side effects and returns
            // a string. It answers two questions at once: that InvokeCommand
            // dispatches at all, and that the mod's TryAddCommand registrations
            // survived whatever generated the table.
            var result = QuantumConsoleProcessor.InvokeCommand("pbj.net-status");
            Debug.Log("[pb-and-j] qc probe | InvokeCommand('pbj.net-status') -> "
                + (result == null ? "<null>" : result.ToString()));
        }
    }
}
#endif
